//File generated by /multi-version.js 

import { CdrLink as CdrLink010 } from '/Users/laharpe/REI/rei-cedar-proving-grounds/cedar-packages/cdr-link/0.1.0/cdr-link.js';
import { CdrLink as CdrLink020 } from '/Users/laharpe/REI/rei-cedar-proving-grounds/cedar-packages/cdr-link/0.2.0/cdr-link.js';
import { CdrLink as CdrLink100 } from '/Users/laharpe/REI/rei-cedar-proving-grounds/cedar-packages/cdr-link/1.0.0/cdr-link.js';

export default {
  CdrLink010,
  CdrLink020,
  CdrLink100
}