//File generated by /multi-version.js 

import { CdrButton as CdrButton003 } from '/Users/laharpe/REI/rei-cedar-proving-grounds/cedar-packages/cdr-button/0.0.3/cdr-button.js';
import { CdrButton as CdrButton010 } from '/Users/laharpe/REI/rei-cedar-proving-grounds/cedar-packages/cdr-button/0.1.0/cdr-button.js';
import { CdrButton as CdrButton100 } from '/Users/laharpe/REI/rei-cedar-proving-grounds/cedar-packages/cdr-button/1.0.0/cdr-button.js';
import { CdrButton as CdrButton102 } from '/Users/laharpe/REI/rei-cedar-proving-grounds/cedar-packages/cdr-button/1.0.2/cdr-button.js';

export default {
  CdrButton003,
  CdrButton010,
  CdrButton100,
  CdrButton102
}