//File generated by /multi-version.js 

import { CdrRating as CdrRating010 } from '/Users/laharpe/REI/rei-cedar-proving-grounds/cedar-packages/cdr-rating/0.1.0/cdr-rating.js';
import { CdrRating as CdrRating011 } from '/Users/laharpe/REI/rei-cedar-proving-grounds/cedar-packages/cdr-rating/0.1.1/cdr-rating.js';
import { CdrRating as CdrRating100alpha3 } from '/Users/laharpe/REI/rei-cedar-proving-grounds/cedar-packages/cdr-rating/1.0.0-alpha.3/cdr-rating.js';

export default {
  CdrRating010,
  CdrRating011,
  CdrRating100alpha3
}